name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Linters
        run: pip install "ruff>=0.1.4" "pre-commit>=3.3.3,<4.0.0"
      - name: Run Linters
        run: make lint
